export default {
  isDsf: true,
  isBusiness: true,
  designId: "",
  caption: "dataviewbusinesskeytrades207",
  visible: true,
  forceHidden: false,
  metadata: null,
  classList: [],
  noPadding: false,
  slots: [{ name: "default", controls: [] }],
  tbNoPadding: false,
  lrNoPadding: false,
  local: null,
  staticValue: null,
  backgroundConfig: null,
  isBlockControl: false,
  development: { attrs: {} },
  anchorKey: "",
  designerInfo: null,
  metadataAttach: {},
  defer: "inited",
  designProxy: true,
  designDisabledProps: null,
  designOnlySlot: false,
  designInductionSlot: true,
  designShowMarkCaption: true,
  designShowMarkInfo: true,
  designShowMarkRemove: true,
  designShowMarkDragDrop: true,
  desCopyedChangeCaption: true,
  boxOutsetShadowConfig: { flag: false, boxShadow: "0px 0px 10px 0px red" },
  boxInsetShadowConfig: { flag: false, boxShadow: "inset 0px 0px 10px 0px red" },
  enterAnimate: { animation: [], duration: 2, delay: 0, repeat: 1 },
  enableDependentRun: false,
  isDataViewControl: true,
  executeFnScope: "",
  executeFnComp: {},
  fakeCodeName: "图文组件207",
  fontSize: 16,
  fontWeight: 500,
  excelData: [
    ["字段名", "name", "num", "value_d", "value_e"],
    ["字段名描述", "名称", "数量", "单位", "同比"],
    [null, "牛群净增", "11", "%", "13"],
    [null, "泌乳天数", "280", "天", "-21"],
  ],
  padding: [10, 10, "20", 10],
  margin: [0, "20", 0, 0],
  height: "100%",
  width: "100%",
  prop_mainColor: "#83bff6",
  prop_viceColor: "#00CED1",
  prop_backgroundColor: "transparent",
  blink: true,
  dur: 0.5,
  isVertical: true,
  dataType: "excel",
  combineTable: { name: "", active: "combineLedger", id: "", adHocQueries: null, url: "/metadata/macrodata/kiv/queryMetadataTableData", params: null },
  interface: { _id: "", code: null, url: "", label: "", filed: [] },
  dataSource: { _id: "", code: null, url: "", label: "", filed: [] },
  dataURL: "",
  configAttachRequestHeaders: [],
  configAttachRequestParams: [],
  combineTableHeaders: [],
  combineTableParams: [],
  dataSourceHeaders: [],
  dataSourceParams: [],
  isHandlerRefresh: false,
  hasEventRelative: true,
  eventRelativeDeal: { mounted: { relatives: [], fn: "" }, dataLoad: { relatives: [], fn: "" }, load: { relatives: [], fn: "" }, click: { relatives: [], fn: "" } },
  dealDataFunction: "function $dealData(data,self) {\n// data 接口返回数据\n// self 当前组件\n}",
  dealDataList: [],
  interfaceMethod: "get",
  interInterfaceHttpJSONFlag: false,
  interfaceHttpConfig: null,
  interfaceMapFieldList: [],
  mapFieldList: [],
  datasourceMapFieldList: [],
  excelMapFieldList: [
    { name: "名称", value: "name" },
    { name: "数量", value: "num" },
    { name: "单位", value: "value_d" },
    { name: "同比", value: "value_e" },
  ],
  dataDivideSet: [],
  divideDataMapList: [],
  dataReplaceText: [],
  pageConfig: {
    isPage: false,
    pageSize: 10,
    isRequest: true,
    selectStyle: "default",
    vAlign: "center",
    hAlign: "center",
    margin: [0, 0, 0, 0],
    padding: [0, 0, 0, 0],
    height: "50",
    fontSize: "14",
    fontFamily: "Microsoft Yahei",
    arrowDirection: "row",
    arrowType: "circle",
    arrowDistance: 20,
    btnList: [
      { name: "刷新重置", value: "slot", show: true },
      { name: "前一页", value: "prev", show: true },
      { name: "页码", value: "pager", show: true },
      { name: "后一页", value: "next", show: true },
      { name: "跳转第几页", value: "jumper", show: true },
      { name: "总数", value: "total", show: true },
    ],
    fontWeight: "normal",
    fontStyle: null,
    textDecoration: null,
  },
  hoverConfig: { isHoverFlag: false, bgEffect: {} },
  singleSizeType: "auto",
  propStyleFakeSelect: "all",
  styleMapKey: "dataviewKeyTrades",
  staticData: [
    { name: "工业增加值", num: "180", value: "148.6", percent: "-11.9" },
    { name: "农业增加值", num: "280", value: "168.6", percent: "+9.9" },
    { name: "互联网增加值", num: "380", value: "118.6", percent: "+13.9" },
    { name: "房产增加值", num: "1110", value: "128.6", percent: "-12.3" },
  ],
  wholeBackground: {},
  config: {
    colors: [
      { active: "custom", custom: { image: "/upload/file/png/afa1dd3a7fb04ed2b979b66cbfc427f7", size: "cover", repeat: "no-repeat", position: "center", static: true } },
      { active: "custom", custom: { image: "/upload/file/png/1c7994ab0b6e4b299baf9b077458d876", size: "cover", repeat: "no-repeat", position: "center", static: true } },
      { active: "custom", custom: { image: "/upload/file/png/a32cd2fc84294415a1a2efa518d595ab", size: "cover", repeat: "no-repeat", position: "center", static: true } },
      { active: "custom", custom: { image: "/upload/file/png/f33dd1e42aa2454597dfaa4982f38c45", size: "cover", repeat: "no-repeat", position: "center", static: true } },
    ],
  },
  isShowIcon: false,
  imgWidth: "100",
  imgHeight: "100",
  imgRelativeX: "0",
  imgRelativeY: "0",
  backgroundConfigs: [
    {
      margin: [],
      padding: [],
      wH: ["", ""],
      relative: ["0"],
      isRelative: [],
      borderRadius: [],
      bgImgObj: {
        active: "pattern",
        imageType: "board",
        pattern: {
          image: "/dsfa.prototype.bimage/edit/upload/file/png/c2fd513de8f34d47a5def52e9b58cb45",
          size: "contain",
          repeat: "no-repeat",
          position: ["center", "bottom"],
          customW: "100%",
          customH: "100%",
          customX: "center",
          customY: "center",
          isCustomPosition: false,
          animation: {
            name: ["dvDynamicOpacity", "dvJumpUpDown"],
            attrList: [
              { delay: 0, duration: 2.5, range: [0.7, 1], value: "dvDynamicOpacity", label: "动态渐变" },
              { value: "dvJumpUpDown", label: "上下跳动", delay: 0, duration: 2.5, jumpHeight: -2 },
            ],
          },
          width: "100%",
          height: "100%",
        },
        color: { type: "color", image: "", isTheme: true, theme: "main", value: "" },
        custom: {
          image: "/upload/file/png/4002c4523c6a465a964b02fce5a4b4fe",
          size: "contain",
          repeat: "no-repeat",
          position: ["center", "center"],
          customW: "100%",
          customH: "100%",
          customX: "center",
          customY: "center",
          isCustomPosition: false,
          static: true,
          animation: { name: [], attrList: [] },
        },
        linear: {
          angle: 0,
          point: [
            { length: 0, color: "rgba(255,255,255,0)" },
            { length: 100, color: "#000" },
          ],
        },
        radial: {
          shape: "circle",
          size: "farthest-corner",
          position: [50, 50],
          point: [
            { length: 0, color: "rgba(255,255,255,0)" },
            { length: 100, color: "#000" },
          ],
        },
        blurBackdrop: 0,
      },
    },
  ],
  itemWidth: "120px",
  itemHeight: "80px",
  direction: true,
  itemAlign: "center",
  isCancelSelect: false,
  isSelectEffect: false,
  defaultSelect: "无",
  selectBgEffect: {},
  contentWidth: "100%",
  totalMargin: ["10", "10", 0, "10"],
  totalPadding: ["40", 0, 0, 0],
  margins: [],
  paddings: [],
  align: "center",
  verticalAlign: "center",
  optionsLayout: "2",
  totalItemAlign: "center",
  configMapRelations: {
    attachArr: [
      {
        uuid: "fYMybtatlNNUtLZa",
        title: "name",
        layoutMethods: 24,
        error: false,
        nameColor: "rgba(255,255,255,1)",
        nameFontSize: "18",
        nameRuleList: [],
        field: "",
        valueFontSize: "20",
        valueColor: "rgba(255,255,255,1)",
        valueRuleList: [],
        unit: "",
        unitRuleList: [],
        style: {
          nameColor: "rgba(255,255,255,1)",
          nameFontSize: "18",
          nameFontFamily: "Alibaba-PuHuiTi-Regular",
          nameFontWeight: "normal",
          nameFontStyle: "",
          nameTextDecoration: "",
          nameTextShadow: "",
          nameMarginTop: 0,
          nameMarginRight: 0,
          nameMarginBottom: 0,
          nameMarginLeft: 0,
          nameTextAlign: "left",
          lineNum: 0,
          lineBreak: 0,
          valueFontSize: "20",
          valueColor: "rgba(220,240,255,1)",
          valueFontWeight: "normal",
          valueFontStyle: "",
          valueTextDecoration: "",
          valueTextShadow: "",
          valueFontFamily: "Alibaba-PuHuiTi-Regular",
          valueMarginTop: 0,
          valueMarginRight: 0,
          valueMarginBottom: 0,
          valueMarginLeft: 10,
          isBar: false,
          barConfig: {
            width: "100",
            height: "10",
            borderRadius: "4",
            bgColor: "rgba(53,143,248,1)",
            basicBgColor: "#DCE3F3",
            showValue: false,
            bgColorRuleList: [],
            pointInfo: { type: "no", color: "rgba(255,255,255,1)", baseColor: "rgba(255,255,255,0.3)", isBreathe: false },
            animation: { flag: false, duration: 3 },
            isGradient: false,
            gradientColors: ["#37a2da", "#37a2da"],
          },
          digitalWholeConfig: {
            digitalStyle: { color: "#fff", fontWeight: "normal", fontStyle: "normal", textDecoration: "none", fontFamily: "Microsoft Yahei", fontSize: "20", numberWidth: "auto" },
            textAlign: { hAlign: "center" },
            fontMargin: [0, 0, 0, 0],
            fontPadding: [0, 0, 0, 0],
            isTotalDigital: false,
            singleBackgroundConfig: {},
            decimals: 0,
            isShowZero: true,
            unitTransform: "",
            separator: "",
            config: { duration: 3000, autoplay: false, useEasing: true },
            isCycle: false,
            cycleSpaceTime: 3000,
            fontSize: "20",
            color: "rgba(220,240,255,1)",
            fontBgColor: null,
            digitalFont: false,
            fontFamily: "Microsoft Yahei",
            fontStyle: "",
            textDecoration: "normal",
            align: "center",
            isFontBold: false,
            fontWeight: "normal",
          },
          unitColor: "rgba(220,240,255,1)",
          unitFontSize: "",
          unitFontFamily: "Alibaba-PuHuiTi-Regular",
          unitFontWeight: "",
          unitFontStyle: "",
          unitTextDecoration: "",
          unitTextShadow: "",
          unitGap: 5,
          relativeTop: -19,
          relativeRight: 0,
          relativeBottom: 0,
          relativeLeft: 0,
          paddingTop: 0,
          paddingRight: 0,
          paddingBottom: 0,
          paddingLeft: 0,
          align: "center",
          verticalAlign: "flex-start",
          height: "auto",
          lineHeight: "normal",
          valueUnitTransform: "",
          valueToRuleFlag: true,
          unitToRuleFlag: false,
          valueBoldFlag: false,
        },
        nameColorObj: { defaultValue: "rgba(255,255,255,1)", ruleList: [] },
        nameIconObj: { defaultValue: "", ruleList: [] },
        nameImgObj: { defaultValue: "", ruleList: [] },
        nameShowType: "icon",
        nameShowPosition: "before",
        valueShowType: "icon",
        valueShowPosition: "before",
        valueColorObj: { defaultValue: "rgba(220,240,255,1)", ruleList: [] },
        valueIconObj: { defaultValue: "", ruleList: [] },
        valueImgObj: { defaultValue: "", ruleList: [] },
      },
      {
        uuid: "V912QG4fDzTVxYjN",
        title: "",
        layoutMethods: 24,
        error: false,
        nameColor: "rgba(255,255,255,1)",
        nameFontSize: "",
        nameRuleList: [],
        field: "num",
        valueFontSize: "24",
        valueColor: "rgba(255,255,255,1)",
        valueRuleList: [],
        unit: "value_d",
        unitRuleList: [],
        style: {
          nameColor: "rgba(255,255,255,1)",
          nameFontSize: "",
          nameFontFamily: "Alibaba-PuHuiTi-Regular",
          nameFontWeight: "",
          nameFontStyle: "",
          nameTextDecoration: "",
          nameTextShadow: "",
          nameMarginTop: 0,
          nameMarginRight: 0,
          nameMarginBottom: 0,
          nameMarginLeft: 0,
          nameTextAlign: "left",
          lineNum: 0,
          lineBreak: 0,
          valueFontSize: "24",
          valueColor: "rgba(220,240,255,1)",
          valueFontWeight: "normal",
          valueFontStyle: "",
          valueTextDecoration: "",
          valueTextShadow: "",
          valueFontFamily: "Alibaba-PuHuiTi-Regular",
          valueMarginTop: 0,
          valueMarginRight: 0,
          valueMarginBottom: 0,
          valueMarginLeft: 10,
          isBar: false,
          barConfig: {
            width: "100",
            height: "10",
            borderRadius: "4",
            bgColor: "rgba(53,143,248,1)",
            basicBgColor: "#DCE3F3",
            showValue: false,
            bgColorRuleList: [],
            pointInfo: { type: "no", color: "rgba(255,255,255,1)", baseColor: "rgba(255,255,255,0.3)", isBreathe: false },
            animation: { flag: false, duration: 3 },
            isGradient: false,
            gradientColors: ["#37a2da", "#37a2da"],
          },
          digitalWholeConfig: {
            digitalStyle: { color: "rgba(220,240,255,1)", fontWeight: "normal", fontStyle: "", textDecoration: "", fontFamily: "Alibaba-PuHuiTi-Regular", fontSize: "24", numberWidth: "auto" },
            textAlign: { hAlign: "center" },
            fontMargin: [0, 0, 0, 0],
            fontPadding: [0, 0, 0, 0],
            isTotalDigital: true,
            singleBackgroundConfig: {},
            decimals: 0,
            isShowZero: true,
            unitTransform: "",
            separator: "",
            config: { duration: 3000, autoplay: true, useEasing: true },
            isCycle: false,
            cycleSpaceTime: 3000,
            fontSize: "24",
            color: "rgba(220,240,255,1)",
            fontBgColor: null,
            digitalFont: false,
            fontFamily: "Microsoft Yahei",
            fontStyle: "",
            textDecoration: "",
            align: "center",
            isFontBold: false,
            fontWeight: "normal",
          },
          unitColor: "rgba(220,240,255,1)",
          unitFontSize: "16",
          unitFontFamily: "Alibaba-PuHuiTi-Regular",
          unitFontWeight: "normal",
          unitFontStyle: "",
          unitTextDecoration: "",
          unitTextShadow: "",
          unitGap: 2,
          relativeTop: -21,
          relativeRight: 0,
          relativeBottom: 0,
          relativeLeft: 0,
          paddingTop: 0,
          paddingRight: 0,
          paddingBottom: 0,
          paddingLeft: 0,
          align: "center",
          verticalAlign: "center",
          height: "auto",
          lineHeight: "normal",
          valueUnitTransform: "",
          valueToRuleFlag: true,
          unitToRuleFlag: false,
          valueBoldFlag: true,
        },
        nameColorObj: { defaultValue: "rgba(255,255,255,1)", ruleList: [] },
        nameIconObj: { defaultValue: "", ruleList: [] },
        nameImgObj: { defaultValue: "", ruleList: [] },
        nameShowType: "icon",
        nameShowPosition: "before",
        valueShowType: "icon",
        valueShowPosition: "before",
        valueColorObj: { defaultValue: "rgba(220,240,255,1)", ruleList: [] },
        valueIconObj: { defaultValue: "", ruleList: [] },
        valueImgObj: { defaultValue: "", ruleList: [] },
        valueFontWeight: "",
      },
      {
        uuid: "yxibI0K0YckkWFf2",
        title: "同比",
        layoutMethods: 24,
        error: false,
        nameColor: "rgba(255,255,255,1)",
        nameFontSize: "18",
        nameRuleList: [],
        field: "value_e",
        valueFontSize: "18",
        valueColor: "rgba(255,255,255,1)",
        valueRuleList: [
          {
            id: "0TIWsVRv",
            type: "text",
            ruleConfig: { field: "value_e", condition: ">", diffValue: "0", oldRule: "" },
            attr: { id: "R6oZnvWj", content: "", color: "rgba(244, 2, 2, 1)", fontSize: "", fontFamily: "Microsoft Yahei", fontWeight: "normal", fontStyle: "", textDecoration: "" },
          },
          {
            id: "jXG1XFlB",
            type: "icon",
            ruleConfig: { field: "value_e", condition: ">", diffValue: "0", oldRule: "" },
            attr: { id: "7P3UXqUF", position: "before", color: "rgba(244, 2, 2, 1)", icon: "up", fontSize: "" },
          },
          {
            id: "IoTI8xC3",
            type: "text",
            ruleConfig: { field: "value_e", condition: "<", diffValue: "0", oldRule: "" },
            attr: { id: "uKfruXh1", content: "", color: "rgba(6, 184, 41, 1)", fontSize: "", fontFamily: "Microsoft Yahei", fontWeight: "normal", fontStyle: "", textDecoration: "" },
          },
          {
            id: "P7cqQrZ1",
            type: "icon",
            ruleConfig: { field: "value_e", condition: "<", diffValue: "0", oldRule: "" },
            attr: { id: "CSIAvIv6", position: "before", color: "rgba(6, 184, 41, 1)", icon: "down", fontSize: "" },
          },
        ],
        unit: "%",
        unitRuleList: [
          {
            id: "aAVHuEJj",
            type: "text",
            ruleConfig: { field: "value_e", condition: ">", diffValue: "0", oldRule: "" },
            attr: { id: "XvbhybJu", content: "", color: "rgba(244, 2, 2, 1)", fontSize: "", fontFamily: "Microsoft Yahei", fontWeight: "normal", fontStyle: "", textDecoration: "" },
          },
          {
            id: "uGBRGERg",
            type: "text",
            ruleConfig: { field: "value_e", condition: "<", diffValue: "0", oldRule: "" },
            attr: { id: "odSBfI7f", content: "", color: "rgba(6, 184, 41, 1)", fontSize: "", fontFamily: "Microsoft Yahei", fontWeight: "normal", fontStyle: "", textDecoration: "" },
          },
        ],
        style: {
          nameColor: "rgba(255,255,255,1)",
          nameFontSize: "18",
          nameFontFamily: "Alibaba-PuHuiTi-Regular",
          nameFontWeight: "normal",
          nameFontStyle: "",
          nameTextDecoration: "",
          nameTextShadow: "",
          nameMarginTop: 0,
          nameMarginRight: 0,
          nameMarginBottom: 0,
          nameMarginLeft: 0,
          nameTextAlign: "left",
          lineNum: 0,
          lineBreak: 0,
          valueFontSize: "18",
          valueColor: "rgba(220,240,255,1)",
          valueFontWeight: "normal",
          valueFontStyle: "",
          valueTextDecoration: "",
          valueTextShadow: "",
          valueFontFamily: "Alibaba-PuHuiTi-Regular",
          valueMarginTop: 0,
          valueMarginRight: 0,
          valueMarginBottom: 0,
          valueMarginLeft: 10,
          isBar: false,
          barConfig: {
            width: "100px",
            height: "10px",
            borderRadius: "0",
            bgColor: "rgba(53,143,248,1)",
            basicBgColor: "rgba(220,227,243,0.2)",
            showValue: false,
            bgColorRuleList: [],
            pointInfo: { type: "no", color: "rgba(255,255,255,1)", baseColor: "rgba(255,255,255,0.3)", isBreathe: false },
            animation: { flag: false, duration: 3 },
          },
          digitalWholeConfig: {
            digitalStyle: { color: "rgba(244, 2, 2, 1)", fontWeight: "normal", fontStyle: "", textDecoration: "", fontFamily: "Alibaba-PuHuiTi-Regular", fontSize: "18", numberWidth: "auto" },
            textAlign: { hAlign: "center" },
            fontMargin: [0, 0, 0, 0],
            fontPadding: [0, 0, 0, 0],
            isTotalDigital: false,
            singleBackgroundConfig: {},
            decimals: 0,
            isShowZero: true,
            unitTransform: "",
            separator: "",
            config: { duration: 3000, autoplay: false },
            isCycle: false,
            cycleSpaceTime: 3000,
            color: "rgba(220,240,255,1)",
            fontWeight: "normal",
            fontStyle: "",
            fontFamily: "Microsoft Yahei",
            fontSize: "18",
            isFontBold: false,
          },
          unitColor: "rgba(220,240,255,1)",
          unitFontSize: "18",
          unitFontFamily: "Alibaba-PuHuiTi-Regular",
          unitFontWeight: "normal",
          unitFontStyle: "",
          unitTextDecoration: "",
          unitTextShadow: "",
          unitGap: "0",
          relativeTop: -24,
          relativeRight: 0,
          relativeBottom: 0,
          relativeLeft: 0,
          paddingTop: 0,
          paddingRight: 0,
          paddingBottom: 0,
          paddingLeft: 0,
          align: "center",
          verticalAlign: "center",
          height: "auto",
          lineHeight: "normal",
          valueUnitTransform: "",
          valueToRuleFlag: true,
          unitToRuleFlag: false,
        },
      },
    ],
    dynamicConfigs: [
      { name: "名称/字段", key: "title", type: "fieldInput" },
      { name: "值字段", key: "field", type: "fieldInput", isMust: true },
      { name: "单位", key: "unit", type: "fieldInput" },
    ],
    __changeType__: "indexKeyTradesStyle",
  },
  ctrlType: "dsf.dataviewbusinesskeytrades",
  ctrlName: "DsfDataViewBusinessKeyTrades",
};
